### ISSUE TITLE
additional pod labels 

### ISSUE THREAD

**Issue by elihai-risk** [SchwarzIT/node-red-chart#130]
### Is your feature request related to a problem? Please describe.

we want to have the ability to add more labels 

### Describe the solution you'd like

add here option to add more labels  : https://github.com/SchwarzIT/node-red-chart/blob/main/charts/node-red/templates/deployment.yaml#L27

fo example:
spec:
    metadata:
      labels:
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}

### Describe alternatives you've considered

don't have

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dirien** [comment]
Hi @elihai-risk,

thanks for the feature idea! Yes ofc! I created a new release for this 0.18.0!

```yaml
# -- Labels to add to the node-red pod. default: {}
podLabels: {}
```

Would love to hear your feedback, when you had time to test it!

**Comment by Aviv-Jacobs** [comment]
Hi, @dirien 
First of all - thanks for the quick work on the feature we asked.
We need to configure the admin user in order to use the chart to upload flows automatically.
It's not clear from the documentation how to configure the settings.
should I just put the default settings with the changes I want under the settings section in the values.yaml file or should I create a config-map? 

Thank you

**Comment by dirien** [comment]
Hi @Aviv-Jacobs,

thanks for your feedback! Yes we use a config map with the settings.js inside

```yaml
settings:
  # name of the volume, free to use
  name: settings-js
  configMapName: settings-node-red-1
```

And the `sidecar` to refresh the flow, without the need to restart `node-red`.

```yaml
  sidecar:
    enabled: true
    securityContext:
      runAsUser: 1000
    env:
      username: "operator"
      label: "node_red_flows"
      label_value: "node-red-1"
```

What I can offer to you is that we, @Kaktor and me, organise a little meeting and show you our setup here at the Schwarz Group! If you are interested, just drop me a mail `engin.diri@mail.schwarz`!
