### ISSUE TITLE
Support InitContainer for node-red pod

### ISSUE THREAD

**Issue by dirien** [SchwarzIT/node-red-chart#22]
In the values.yaml we should add a key initcontainer to define a whole initcontainer. In the template we can reference on it with `toYaml`

**Comment by Langhalsdino** [comment]
I would recommend to classify this a bug, since the helm chart is not properly working on EKS or GKE in persistent mode.

## How to reproduce the error

```bash
helm repo add node-red https://schwarzit.github.io/node-red-chart/
helm repo update
helm upgrade --install node-red-test node-red/node-red -f values.yml --namespace dev --version 0.3.2
```

While the values.yml is defined as follows:

```yaml
replicaCount: 1

env:
  - name: "TZ"
    value: "UTC"
  - name: "NODE_RED_ENABLE_SAFE_MODE"
    value: "false"
  - name: "NODE_RED_ENABLE_PROJECTS"
    value: "false"
  - name: "FLOWS"
    value: "flows.json"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi

ingress:
  enabled: false

resources:
  limits:
    cpu: 100m
    memory: 256Mi

service:
  type: NodePort
  port: 1880
```
