### ISSUE TITLE
persistence: Keep pvc when uninstalling helm chart

### ISSUE THREAD

**Issue by hinrichd** [SchwarzIT/node-red-chart#227]
### Is your feature request related to a problem? Please describe.

Thank you for maintaining the nodered chart. 

I want to reuse an existing pvc in case I have to reinstall the chart and do not want to lose my existing flows and data. 
Actually a "helm uninstall nodered" will delete the pvc resource and can not be reused by the existing claim key/value.
```
Helm Values Sample
#STORAGE
persistence:
  # -- Use persistent volume to store data
  enabled: true
  ## node-red data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provik sioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # -- Type of persistent volume claim
  storageClass: "sp-test"
  ##
  ## If you want to reuse an existing claim, you can pass the name of the PVC using
  ## the existingClaim variable
  # -- Use an existing PVC to persist data
  existingClaim: pvc-3c33e0d7-d3d4-42ea-9dd1-9ec36b9faf45
  # -- Persistence access mode
  accessMode: ReadWriteOnce
  # -- Size of persistent volume claim
  size: 5Gi
```

### Describe the solution you'd like

Do not delete PVC resources when performing helm uninstall when key "persistences.keep=enabled" is set. 

### Describe alternatives you've considered

Alternatives to this would be a general way to import flows as also install nodes from configmap. I case of an reinstall, pod crash etc. the flows and nodes would be reloaded. 
https://github.com/SchwarzIT/node-red-chart/issues/198

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
