### ISSUE TITLE
Cannot GET /metrics

### ISSUE THREAD

**Issue by janpieper** [SchwarzIT/node-red-chart#319]
### What happened?

Don't think this is a bug, but I am not familiar with Node.js/NodeRED to fully understand how to enable the prometheus metrics.

---

I just realized that the metrics from NodeRED are not available for Prometheus, so I checked what is the problem. I only enabled the metrics via the chart values:

```yaml
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```

But today I read that I also need to install the `node-red-contrib-prometheus-exporter` like described in the chart README: [README > Monitoring](https://github.com/SchwarzIT/node-red-chart/blob/main/charts/node-red/README.md#monitoring-%EF%B8%8F).

I tried to do so by enabling the sidecar container and added `node-red-contrib-prometheus-exporter` to `sidecar.extraNodeModules`.

After deploying this to my K8s, there now is the sidecar container for the node-red pod, but the node module is still not installed :thinking: 

![Screenshot from 2024-02-23 12-39-04](https://github.com/SchwarzIT/node-red-chart/assets/426371/b34fd5fc-1979-438e-bed1-5042051763b2)

Requesting `:1880/metrics` gives me `Cannot GET /metrics` :man_shrugging: 

### How can we reproduce this?

```yaml
sidecar:
  enabled: true
  extraNodeModules:
    - node-red-contrib-prometheus-exporter

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
```

### Helm Chart version

```bash
0.29.0
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
