### ISSUE TITLE
Persisence-related chart values not being respected

### ISSUE THREAD

**Issue by rossigee** [SchwarzIT/node-red-chart#321]
### What happened?

I expected to be able to define various aspects of the PVC manifest.

It turns out that the docs and `values.yaml` are out-of-date/incorrect, as only the `persitence.enabled` and an undocumented `subPath` value are being respected.

### How can we reproduce this?

https://github.com/search?q=repo%3ASchwarzIT%2Fnode-red-chart%20persistence&type=code

### Helm Chart version

```bash
$ helm -n nodered list
NAME   	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART          	APP VERSION
nodered	nodered  	4       	2024-03-01 09:03:22.916041598 +0000 UTC	deployed	node-red-0.28.1	3.0.2      
```
```


### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

As a workaround I've simply disabled persistence in the chart and created the PVC separately.

**Comment by dirien** [comment]
Hey @rossigee,

Can you elaborate more on the issue and why you had to use the workaround you went?

**Comment by rossigee** [comment]
The `values.yaml` (without comments) [suggests](https://github.com/SchwarzIT/node-red-chart/blob/bf00422730539a60692a3a0191ec23696840ad01/charts/node-red/values.yaml#L131C1-L153C17) we configure persistence using values in the chart like this:

```yaml
persistence:
  enabled: false
  # storageClass: "-"
  # existingClaim: your-claim
  accessMode: ReadWriteOnce
  size: 5Gi
  keepPVC: false
```

However, the template file for [the deployment](https://github.com/SchwarzIT/node-red-chart/blob/bf00422730539a60692a3a0191ec23696840ad01/charts/node-red/templates/deployment.yaml#L164) uses undocumented `subPath` and `existingClaim` attributes, and it mounts the `/data` volume regardless of the value of `enabled` or not.

It took me a while to figure that out. Perhaps an update to the README would be useful? In the end it was easily achieved using this:

```yaml
    persistence:
      enabled: true
      existingClaim: nodered-data
```
