### ISSUE TITLE
Confusion about securityContext when creating SSH keys

### ISSUE THREAD

**Issue by natcl** [SchwarzIT/node-red-chart#420]
### What happened?

I am testing this helm chart and enabled Node-RED's project mode. When Project mode is enabled you can ask Node-RED to generate an SSH key to link it to a GIT repository. With the default securityContext values (see below) creating this key fails with an error saying the user 10003 doesn't have access. I assume this is because the Node-RED user (1000) is trying to create the files in a folder that is owned by user 10003.
I fixed it by changing the securityContext user and group to 1000 but was wondering if this was the best approach  ?

```yaml
# -- Pod Security Context see [values.yaml](values.yaml)
podSecurityContext:
  # -- node-red group is 1000
  fsGroup: 1000
  # -- node-red user is 1000
  runAsUser: 1000

# -- Security Context see [values.yaml](values.yaml)
securityContext:
  privileged: false
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsGroup: 10003
  runAsUser: 10003
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL
 ```

### How can we reproduce this?

See above.

### Helm Chart version

```bash
0.34.0
```

### Search

- [x] I did search for other open and closed issues before opening this.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
